#!/usr/bin/env bash
# a script that configures a new Ubuntu machine using an answer file
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
sudo chown -R $USER:$USER /var/www/html/
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
