#!/usr/bin/env bash
# a script that configures a new Ubuntu machine using an answer file
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
