#!/usr/bin/env bash
# a script that configures a new Ubuntu machine using an answer file
# sudo apt update -y
# sudo apt upgrade -y
# sudo apt install nginx -y
# sudo service nginx start
# sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
# echo "server {
#     server_name hazemit.tech www.hazemit.tech;
#     location /redirect_me {
#         return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI permanent;
#     }
# }" > /etc/nginx/sites-available/default
# sudo service nginx restart


sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '53i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
