#!/usr/bin/env bash
# a script that redirects a page to another page
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '53i\ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
