#!/usr/bin/env bash
# a script that configures a new Ubuntu machine using an answer file
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html/
touch /var/www/html/404.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '53i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sed -i '54i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
