#!/usr/bin/env bash
# Double the number of webservers
sudo apt update -y
sudo apt install nginx -y
sudo service nginx start

sudo chown -R "$USER":"$USER" /var/www/html
touch /var/www/html/404.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo bash -c 'cat <<EOF> /etc/nginx/sites-enabled/default
	server {
	    listen 80 default_server;
        listen [::]:80 default_server;
	    root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        
        add_header X-Served-By $hostname;
    
        location / {
            try_files $uri $uri/ =404;
	    }
        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        error_page 404 /error_404.html;
	}
EOF'
sudo service nginx restart
