#!/usr/bin/env bash
# A script to interactive with signals

suicide()
{
    rm /var/run/myscript.pid
    exit
}

echo "$$" > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2

    trap 'echo "I hate the kill command" && suicide' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'suicide' SIGQUIT
done
