#!/usr/bin/env bash
# Bash script that configures an Ubuntu server to resolve URLs to IPv4 addresses
cp /etc/hosts ~/hosts.bkp
sed -i -e '$a127.0.0.2        localhost' ~/hosts.bkp
sed -i -e '$a8.8.8.8          facebook.com' ~/hosts.bkp
cp -f ~/hosts.bkp /etc/hosts
